title: Hello, world! I'm Shubham jha
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://whoamishubham.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shubham Jha # add your name
author-img: shubham.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: whoami_shubham # add your Twitter handle
social-facebook: whoami.shubham # add your Facebook handle
social-github: whoami-shubham # add your Github handle
social-linkedin: whoamishubham # add your Linkedin handle
social-email: whoamishubham@gmail.com # add your Email address

# Disqus
discus-identifier: whoami-shubham # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
